// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9scqYetsEESCST8SSIxByAaei2AU79e4',
    appId: '1:616482867820:web:878a38761b7b44f3cae649',
    messagingSenderId: '616482867820',
    projectId: 'e-fira',
    authDomain: 'e-fira.firebaseapp.com',
    storageBucket: 'e-fira.firebasestorage.app',
    measurementId: 'G-J00YWT288F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuwbDuwJddmdFGHr4BKV33MIT06lALm1c',
    appId: '1:616482867820:android:6e4534d98f60a020cae649',
    messagingSenderId: '616482867820',
    projectId: 'e-fira',
    databaseURL: 'https://e-fira-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'e-fira.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9scqYetsEESCST8SSIxByAaei2AU79e4',
    appId: '1:616482867820:web:381e6e29e7971ce7cae649',
    messagingSenderId: '616482867820',
    projectId: 'e-fira',
    authDomain: 'e-fira.firebaseapp.com',
    databaseURL: 'https://e-fira-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'e-fira.firebasestorage.app',
    measurementId: 'G-BTRLJMJBJD',
  );
}
