const List<String> czStationsList = [
  'Praha hl.n.',
  'Praha-Vršovice',
  'Praha-Smíchov',
  'Pardubice hl.n.',
  'Brno hl.n.',
  'Ostrava hl.n.',
  'Olomouc hl.n.',
  'Plzeň hl.n.',
  'Ústí nad Labem hl.n.',
  'Břeclav',
  'Kolín',
  'Česká Třebová',
  'Hradec Králové hl.n.',
  'Jihlava',
  'Zlín střed',
  'Děčín hl.n.',
  'Karlovy Vary hl.n.',
  'Liberec',
  'Mladá Boleslav hl.n.',
  'Teplice v Čechách',
  'Chomutov',
  'Most',
  'Dresden HBF',
  'Berlin HBF',
  ];